// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/core.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GitCloneRequest struct {
	Repository           string   `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GitCloneRequest) Reset()         { *m = GitCloneRequest{} }
func (m *GitCloneRequest) String() string { return proto.CompactTextString(m) }
func (*GitCloneRequest) ProtoMessage()    {}
func (*GitCloneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0acae2797acdd, []int{0}
}

func (m *GitCloneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GitCloneRequest.Unmarshal(m, b)
}
func (m *GitCloneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GitCloneRequest.Marshal(b, m, deterministic)
}
func (m *GitCloneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GitCloneRequest.Merge(m, src)
}
func (m *GitCloneRequest) XXX_Size() int {
	return xxx_messageInfo_GitCloneRequest.Size(m)
}
func (m *GitCloneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GitCloneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GitCloneRequest proto.InternalMessageInfo

func (m *GitCloneRequest) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

type ExecuteCommandsRequest struct {
	Commands             []string `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteCommandsRequest) Reset()         { *m = ExecuteCommandsRequest{} }
func (m *ExecuteCommandsRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteCommandsRequest) ProtoMessage()    {}
func (*ExecuteCommandsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0acae2797acdd, []int{1}
}

func (m *ExecuteCommandsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteCommandsRequest.Unmarshal(m, b)
}
func (m *ExecuteCommandsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteCommandsRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteCommandsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteCommandsRequest.Merge(m, src)
}
func (m *ExecuteCommandsRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteCommandsRequest.Size(m)
}
func (m *ExecuteCommandsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteCommandsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteCommandsRequest proto.InternalMessageInfo

func (m *ExecuteCommandsRequest) GetCommands() []string {
	if m != nil {
		return m.Commands
	}
	return nil
}

func init() {
	proto.RegisterType((*GitCloneRequest)(nil), "proto.GitCloneRequest")
	proto.RegisterType((*ExecuteCommandsRequest)(nil), "proto.ExecuteCommandsRequest")
}

func init() { proto.RegisterFile("proto/core.proto", fileDescriptor_a4b0acae2797acdd) }

var fileDescriptor_a4b0acae2797acdd = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0x2f, 0x4a, 0xd5, 0x03, 0x33, 0x85, 0x58, 0xc1, 0x94, 0x94, 0x74, 0x7a,
	0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x3e, 0x98, 0x97, 0x54, 0x9a, 0xa6, 0x9f, 0x9a, 0x5b, 0x50, 0x52,
	0x09, 0x51, 0xa3, 0x64, 0xc8, 0xc5, 0xef, 0x9e, 0x59, 0xe2, 0x9c, 0x93, 0x9f, 0x97, 0x1a, 0x94,
	0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc7, 0xc5, 0x55, 0x94, 0x5a, 0x90, 0x5f, 0x9c, 0x59,
	0x92, 0x5f, 0x54, 0x29, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x84, 0x24, 0xa2, 0x64, 0xc2, 0x25,
	0xe6, 0x5a, 0x91, 0x9a, 0x5c, 0x5a, 0x92, 0xea, 0x9c, 0x9f, 0x9b, 0x9b, 0x98, 0x97, 0x52, 0x0c,
	0xd3, 0x29, 0xc5, 0xc5, 0x91, 0x0c, 0x15, 0x92, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0c, 0x82, 0xf3,
	0x8d, 0x26, 0x32, 0x72, 0x71, 0x7a, 0xe5, 0x57, 0x26, 0x67, 0x3a, 0xe7, 0x17, 0xa5, 0x0a, 0x59,
	0x71, 0x71, 0xc0, 0xac, 0x15, 0x12, 0x83, 0x38, 0x45, 0x0f, 0xcd, 0x1d, 0x52, 0x62, 0x7a, 0x10,
	0x87, 0xeb, 0xc1, 0x1c, 0xae, 0xe7, 0x0a, 0x72, 0xb8, 0x90, 0x07, 0x17, 0x3f, 0x9a, 0xfd, 0x42,
	0xb2, 0x50, 0x23, 0xb0, 0xbb, 0x0b, 0x97, 0x49, 0x49, 0x6c, 0x60, 0xbe, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0xff, 0x44, 0x0f, 0xb9, 0x3b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JoyciCoreClient is the client API for JoyciCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JoyciCoreClient interface {
	GitClone(ctx context.Context, in *GitCloneRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ExecuteCommands(ctx context.Context, in *ExecuteCommandsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type joyciCoreClient struct {
	cc *grpc.ClientConn
}

func NewJoyciCoreClient(cc *grpc.ClientConn) JoyciCoreClient {
	return &joyciCoreClient{cc}
}

func (c *joyciCoreClient) GitClone(ctx context.Context, in *GitCloneRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.JoyciCore/GitClone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *joyciCoreClient) ExecuteCommands(ctx context.Context, in *ExecuteCommandsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.JoyciCore/ExecuteCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JoyciCoreServer is the server API for JoyciCore service.
type JoyciCoreServer interface {
	GitClone(context.Context, *GitCloneRequest) (*empty.Empty, error)
	ExecuteCommands(context.Context, *ExecuteCommandsRequest) (*empty.Empty, error)
}

// UnimplementedJoyciCoreServer can be embedded to have forward compatible implementations.
type UnimplementedJoyciCoreServer struct {
}

func (*UnimplementedJoyciCoreServer) GitClone(ctx context.Context, req *GitCloneRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GitClone not implemented")
}
func (*UnimplementedJoyciCoreServer) ExecuteCommands(ctx context.Context, req *ExecuteCommandsRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommands not implemented")
}

func RegisterJoyciCoreServer(s *grpc.Server, srv JoyciCoreServer) {
	s.RegisterService(&_JoyciCore_serviceDesc, srv)
}

func _JoyciCore_GitClone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GitCloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoyciCoreServer).GitClone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.JoyciCore/GitClone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoyciCoreServer).GitClone(ctx, req.(*GitCloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JoyciCore_ExecuteCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoyciCoreServer).ExecuteCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.JoyciCore/ExecuteCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoyciCoreServer).ExecuteCommands(ctx, req.(*ExecuteCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JoyciCore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.JoyciCore",
	HandlerType: (*JoyciCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GitClone",
			Handler:    _JoyciCore_GitClone_Handler,
		},
		{
			MethodName: "ExecuteCommands",
			Handler:    _JoyciCore_ExecuteCommands_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core.proto",
}
